export { default as Navbar } from './Navbar';
export { default as About } from './About';
export { default as OurServices } from './OurServices';
export { default as Contact } from './Contact';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as SignUp} from './SignUp';
export { default as Categories} from './Categories';
export { default as ViewDeatails} from './ViewDeatails';
export { default as Footer} from './Footer';
